_wandb:
    value:
        cli_version: 0.24.2
        e:
            v9dy24x018pcq3929rz18yoaa6vvqf3p:
                args:
                    - train
                    - -c
                    - fishy/configs/experiments/evolutionary_computation.yaml
                codePath: main.py
                codePathLocal: main.py
                email: j.r.h.wood98@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                git:
                    commit: 9fe96b7c5fc56feea1a70cdb4eae3e406a6d8c40
                    remote: git@github.com:woodRock/fishy-business.git
                host: Mac.staff.vuw.ac.nz
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/woodj/Desktop/fishy-business/main.py
                python: CPython 3.9.6
                root: /Users/woodj/Desktop/fishy-business
                startedAt: "2026-02-11T06:19:00.328025Z"
                writerId: v9dy24x018pcq3929rz18yoaa6vvqf3p
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 3
                - 16
            "4": 3.9.6
            "5": 0.24.2
            "10":
                - 20
            "12": 0.24.2
            "13": darwin-arm64
batch_size:
    value: 64
benchmark:
    value: true
contrastive_transformation_invariance_learning:
    value: false
crop_enabled:
    value: false
crop_size:
    value: 0.8
data_augmentation:
    value: false
dataset:
    value: species
dropout:
    value: 0.2
early_stopping:
    value: 20
epochs:
    value: 100
epochs_finetune:
    value: 20
epochs_transfer:
    value: 10
figures:
    value: true
file_path:
    value: ""
flip_enabled:
    value: false
hidden_dimension:
    value: 128
k_folds:
    value: 3
label_smoothing:
    value: 0.1
learning_rate:
    value: 0.0001
masked_spectra_modelling:
    value: false
method:
    value: evolutionary
model:
    value: gp
next_peak_prediction:
    value: false
next_spectra_prediction:
    value: false
noise_level:
    value: 0.05
num_augmentations:
    value: 5
num_heads:
    value: 4
num_layers:
    value: 4
num_runs:
    value: 1
ordinal_method:
    value: null
output:
    value: logs/results
peak_parameter_regression:
    value: false
permutation_enabled:
    value: false
regression:
    value: false
run:
    value: 123
scale_enabled:
    value: false
shift_enabled:
    value: false
spectrum_denoising_autoencoding:
    value: false
spectrum_segment_reordering:
    value: false
target_dataset:
    value: null
transfer:
    value: false
transfer_datasets:
    value: null
use_groups:
    value: false
wandb_entity:
    value: victoria-university-of-wellington
wandb_log:
    value: true
wandb_project:
    value: fishy-business
xai:
    value: false
