_wandb:
    value:
        cli_version: 0.24.2
        e:
            26hns3q5urdiwr85p8omduyufx1rkuyk:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                args:
                    - train
                    - -c
                    - fishy/configs/experiments/traditional_methods.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "103275212800"
                email: j.r.h.wood98@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                git:
                    commit: 4eb323eeee0377f5ef2849165f59f0066155ccff
                    remote: git@github.com:woodRock/fishy-business.git
                host: Jesses-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/woodj/Desktop/fishy-business/main.py
                python: CPython 3.9.6
                root: /Users/woodj/Desktop/fishy-business
                startedAt: "2026-02-11T08:27:50.565420Z"
                writerId: 26hns3q5urdiwr85p8omduyufx1rkuyk
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 3
                - 16
                - 61
            "4": 3.9.6
            "5": 0.24.2
            "10":
                - 20
            "12": 0.24.2
            "13": darwin-arm64
        visualize:
            conf_mat:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: conf_mat_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            pr:
                panel_config:
                    fieldSettings:
                        class: class
                        x: recall
                        "y": precision
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Recall Curve
                        x-axis-title: Recall
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: pr_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            roc:
                panel_config:
                    fieldSettings:
                        class: class
                        x: fpr
                        "y": tpr
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: ROC Curve
                        x-axis-title: False positive rate
                        y-axis-title: True positive rate
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: roc_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 64
benchmark:
    value: true
contrastive_transformation_invariance_learning:
    value: false
crop_enabled:
    value: false
crop_size:
    value: 0.8
data_augmentation:
    value: false
dataset:
    value: species
dropout:
    value: 0.2
early_stopping:
    value: 20
epochs:
    value: 100
epochs_finetune:
    value: 20
epochs_transfer:
    value: 10
figures:
    value: true
file_path:
    value: /Users/woodj/Desktop/fishy-business/data/REIMS.xlsx
flip_enabled:
    value: false
hidden_dimension:
    value: 128
k_folds:
    value: 3
label_smoothing:
    value: 0.1
learning_rate:
    value: 0.0001
masked_spectra_modelling:
    value: false
method:
    value: classic
model:
    value: knn
next_peak_prediction:
    value: false
next_spectra_prediction:
    value: false
noise_level:
    value: 0.05
num_augmentations:
    value: 5
num_heads:
    value: 4
num_layers:
    value: 4
num_runs:
    value: 1
ordinal_method:
    value: null
output:
    value: logs/results
peak_parameter_regression:
    value: false
permutation_enabled:
    value: false
regression:
    value: false
run:
    value: 492
scale_enabled:
    value: false
shift_enabled:
    value: false
spectrum_denoising_autoencoding:
    value: false
spectrum_segment_reordering:
    value: false
statistical:
    value: true
target_dataset:
    value: null
transfer:
    value: false
transfer_datasets:
    value: null
use_groups:
    value: false
wandb_entity:
    value: victoria-university-of-wellington
wandb_log:
    value: true
wandb_project:
    value: fishy-business
xai:
    value: false
