_wandb:
    value:
        cli_version: 0.24.2
        e:
            gtmc0ytvfli30uh7zau3yqecr1thrxib:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                args:
                    - train
                    - -m
                    - xgb
                    - -d
                    - batch-detection
                    - --seed
                    - "89"
                    - --benchmark
                    - --figures
                    - --wandb-log
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "216758751232"
                email: j.r.h.wood98@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                git:
                    commit: cd5f295a232dcee8ab940e868111af5eb4bcdd50
                    remote: git@github.com:woodRock/fishy-business.git
                host: Jesses-MacBook-Air-2.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/woodj/Library/Python/3.9/bin/fishy
                python: CPython 3.9.6
                root: /Users/woodj/Desktop/fishy-business
                startedAt: "2026-04-05T16:07:01.820405Z"
                writerId: gtmc0ytvfli30uh7zau3yqecr1thrxib
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 6
                - 53
            "3":
                - 2
                - 3
                - 16
            "4": 3.9.6
            "5": 0.24.2
            "10":
                - 20
            "12": 0.24.2
            "13": darwin-arm64
batch_size:
    value: 64
benchmark:
    value: true
contrastive_transformation_invariance_learning:
    value: false
crop_enabled:
    value: false
crop_size:
    value: 0.8
data_augmentation:
    value: false
dataset:
    value: batch-detection
dropout:
    value: 0.2
early_stopping:
    value: 20
encoder_type:
    value: dense
epochs:
    value: 100
epochs_finetune:
    value: 20
epochs_transfer:
    value: 10
figures:
    value: true
file_path:
    value: null
flip_enabled:
    value: false
hidden_dim:
    value: 128
k:
    value: 2
k_folds:
    value: 3
label_smoothing:
    value: 0.1
learning_rate:
    value: 0.0001
masked_spectra_modelling:
    value: false
method:
    value: classic
model:
    value: xgb
next_peak_prediction:
    value: false
next_spectra_prediction:
    value: false
noise_level:
    value: 0.05
num_augmentations:
    value: 5
num_experts:
    value: 8
num_heads:
    value: 4
num_layers:
    value: 4
num_runs:
    value: 1
ordinal_method:
    value: null
output:
    value: logs/results
peak_parameter_regression:
    value: false
permutation_enabled:
    value: false
regression:
    value: false
run:
    value: 89
scale_enabled:
    value: false
shift_enabled:
    value: false
spectrum_denoising_autoencoding:
    value: false
spectrum_segment_reordering:
    value: false
statistical:
    value: false
target_dataset:
    value: null
transfer:
    value: false
transfer_datasets:
    value: null
use_groups:
    value: false
wandb_entity:
    value: victoria-university-of-wellington
wandb_log:
    value: true
wandb_project:
    value: fishy-business
xai:
    value: false
